package com.neptune.boards.controller;

import com.neptune.boards.dto.ProjectRequestDTO;
import com.neptune.boards.dto.ProjectResponseDTO;
import com.neptune.boards.exception.NeptuneBoardsException;
import com.neptune.boards.service.ProjectService;
import io.swagger.v3.oas.annotations.Operation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/project")
public class ProjectController {
    @Autowired
    private ProjectService service;

    @Operation(
            summary = "Create a Project",
            description = "Create a Project by its UUID generated by the user"
    )
    @PostMapping(path="/{uuid}", produces = {MediaType.APPLICATION_JSON_VALUE})
    public ResponseEntity<ProjectResponseDTO> createBoard(@PathVariable UUID uuid, @RequestBody ProjectRequestDTO boardRequest) {
        return new ResponseEntity<>(service.createBoard(uuid, boardRequest), HttpStatus.OK);
    }

    @GetMapping(path = "/{uuid}", produces = {MediaType.APPLICATION_JSON_VALUE})
    public ResponseEntity<ProjectResponseDTO> getBoard(@PathVariable UUID uuid) throws NeptuneBoardsException {
        return new ResponseEntity<>(service.getBoard(uuid), HttpStatus.OK);
    }

    @GetMapping(path = "/list", produces = {MediaType.APPLICATION_JSON_VALUE})
    public ResponseEntity<List<ProjectResponseDTO>> getAllBoards() {
        return new ResponseEntity<>(service.getAllBoards(), HttpStatus.OK);
    }

    @DeleteMapping(path = "/{uuid}", produces = {MediaType.APPLICATION_JSON_VALUE})
    public ResponseEntity<ProjectResponseDTO> deleteBoard(@PathVariable UUID uuid) throws NeptuneBoardsException {
        return new ResponseEntity<>(service.deleteBoard(uuid), HttpStatus.OK);
    }

    @PutMapping(path="/{uuid}", produces = {MediaType.APPLICATION_JSON_VALUE})
    public ResponseEntity<ProjectResponseDTO> updateBoard(@PathVariable UUID uuid, @RequestBody ProjectRequestDTO boardRequest) throws NeptuneBoardsException {
        return new ResponseEntity<>(service.updateBoard(uuid, boardRequest), HttpStatus.OK);
    }
}
