version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-kanban
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - kanban-net

volumes:
  mysql-data:

networks:
  kanban-net:
